# Generated by Django 5.1.6 on 2025-08-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincode',
            options={'verbose_name': 'Kirish kodi ', 'verbose_name_plural': 'Kirish kodlari'},
        ),
    ]
