# Generated by Django 5.1.6 on 2025-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
