# Generated by Django 5.1.6 on 2025-07-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message_type',
        ),
    ]
