# Generated by Django 5.1.6 on 2025-08-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_notification_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bildirishnoma ', 'verbose_name_plural': 'Bildirishnomalar'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
